tieba:
  tiebaName: 黄河科技学院
  tiebaTopUrl: http://tieba.baidu.com/f/like/furank?ie=utf-8&kw=
  tiebaContentUrl: http://tieba.baidu.com/f?ie=utf-8&kw=
  tiebaContentPageUrl: http://tieba.baidu.com/p/
  #50*50=2500 个帖子
  tiebaContentPageEndNum: 5
  tiebaImageUrl: http://imgsrc.baidu.com/forum/w%3D580/
  tiebaContentIdTopic: tieba_content_id_topic
  tiebaContentNoImageIdTopic: tieba_content_noimage_id_topic
spring:
 redis: 
  database: 2
  host: 123.56.118.135
  password: gaoguangjin
  pool.max-active: 50000
  pool.max-idle: 500
  pool.max-wait: 1000
  pool.min-idle: 300
  port: 6379
  timeout: 100000

qiniu:
    accessKey: aL-Y877Xpt0daNLqkule0TwNTsAFWR0aoYHUTRaA
    secretKey: ngCEeu-AABo_d5GdGJ076bUNSBsntAyisPPeB9ed
    #ggj2010 ggjqn
    bucketName: ggjqn
    domain: http://o8c5x5dg6.bkt.clouddn.com/
  