key:
    #+ip
    blackip: blackip_hset
    #+ip
    ipInvoke: ip_invoke_
    #用户信息缓存
    userInfoLoginName: userinfo_loginname_
    #登陆错误限制
    loginErrorLimit: loginerror_limit_
    #用户token
    userToken: user_token_